const BUSIEST_AIRPORTS = [
  {
    code: 'ATL',
    lat: '33.6558',
    lon: '-84.4333',
    name: 'Hartsfield-Jackson Atlanta International Airport',
    city: 'Atlanta',
    state: 'Georgia',
    country: 'United States',
    woeid: '12522118',
    tz: 'America/New_York',
    phone: '(654) 57 8833',
    type: 'Airports',
    email: '',
    url: 'http://www.atlanta-airport.com/',
    runway_length: '11889',
    elev: '1026',
    icao: 'KATL',
    direct_flights: '253',
    carriers: '60',
  },
  {
    code: 'LAX',
    lat: '33.9456',
    lon: '-118.391',
    name: 'Los Angeles International Airport',
    city: 'Los Angeles',
    state: 'California',
    country: 'United States',
    woeid: '12520706',
    tz: 'America/Los_Angeles',
    phone: '',
    type: 'Airports',
    email: '',
    url: '',
    runway_length: '12091',
    elev: '126',
    icao: 'KLAX',
    direct_flights: '200',
    carriers: '99',
  },
  {
    code: 'DXB',
    lat: '25.2509',
    lon: '55.3629',
    name: 'Dubai International Airport',
    city: 'Dubai',
    state: 'Dubai',
    country: 'United Arab Emirates',
    woeid: '23388362',
    tz: 'Asia/Dubai',
    phone: '+971 4 216 2525',
    type: 'Airports',
    email: '',
    url: 'http://www.dubaiairport.com',
    runway_length: '13123',
    elev: '34',
    icao: 'OMDB',
    direct_flights: '170',
    carriers: '126',
  },
  {
    code: 'ORD',
    lat: '41.9796',
    lon: '-87.8825',
    name: "Chicago O'Hare International Airport",
    city: 'Chicago',
    state: 'Illinois',
    country: 'United States',
    woeid: '12521200',
    tz: 'America/Chicago',
    phone: '',
    type: 'Airports',
    email: '',
    url: 'http://www.flychicago.com/ohare/home.asp',
    runway_length: '13000',
    elev: '668',
    icao: 'KORD',
    direct_flights: '222',
    carriers: '85',
  },
  {
    code: 'LHR',
    lat: '51.4703',
    lon: '-0.45342',
    name: 'London Heathrow Airport',
    city: 'Hounslow',
    state: 'England',
    country: 'United Kingdom',
    woeid: '23382429',
    tz: 'Europe/London',
    phone: '+44 (0)8700 000698',
    type: 'Airports',
    email: '',
    url: 'http://www.heathrowairport.com',
    runway_length: '12802',
    elev: '80',
    icao: 'EGLL',
    direct_flights: '227',
    carriers: '105',
  },
  {
    code: 'CDG',
    lat: '49.0175',
    lon: '2.5564',
    name: 'Charles de Gaulle International Airport',
    city: 'Le Mesnil-Amelot',
    state: 'Ile-de-France',
    country: 'France',
    woeid: '22140453',
    tz: 'Europe/Paris',
    phone: '',
    type: 'Airports',
    email: '',
    url: '',
    runway_length: '11811',
    elev: '387',
    icao: 'LFPG',
    direct_flights: '310',
    carriers: '131',
  },
  {
    code: 'DFW',
    lat: '32.9222',
    lon: '-97.0409',
    name: 'Fort Worth International Airport',
    city: 'Dallas',
    state: 'Texas',
    country: 'United States',
    woeid: '12519786',
    tz: 'America/Chicago',
    phone: '',
    type: 'Airports',
    email: '',
    url: '',
    runway_length: '11388',
    elev: '603',
    icao: 'KDFW',
    direct_flights: '179',
    carriers: '62',
  },
  {
    code: 'AMS',
    lat: '52.3122',
    lon: '4.77511',
    name: 'Schiphol Airport',
    city: 'Schiphol Zuid',
    state: 'North Holland',
    country: 'Netherlands',
    woeid: '22386730',
    tz: 'Europe/Amsterdam',
    phone: '+31-207940800',
    type: 'Airports',
    email: '',
    url: 'http://www.schiphol.com/',
    runway_length: '12467',
    elev: '-11',
    icao: 'EHAM',
    direct_flights: '284',
    carriers: '118',
  },
  {
    code: 'HKG',
    lat: '22.3124',
    lon: '113.929',
    name: 'Hong Kong International Airport',
    city: 'Hong Kong',
    state: 'Hong Kong Island',
    country: 'Hong Kong',
    woeid: '24875607',
    tz: 'Asia/Hong_Kong',
    phone: '+852 2188 7111',
    type: 'Airports',
    email: '',
    url: 'http://www.hongkongairport.com/',
    runway_length: '12467',
    elev: '19',
    icao: 'VHHH',
    direct_flights: '131',
    carriers: '87',
  },
  {
    code: 'FRA',
    lat: '50.0483',
    lon: '8.57041',
    name: 'Frankfurt International Airport',
    city: 'Frankfurt',
    state: 'Hesse',
    country: 'Germany',
    woeid: '22981759',
    tz: 'Europe/Berlin',
    phone: '+49 69 690 0',
    type: 'Airports',
    email: '',
    url: 'http://www.airportcity-frankfurt.de',
    runway_length: '13123',
    elev: '364',
    icao: 'EDDF',
    direct_flights: '337',
    carriers: '131',
  },
];

const DEMO_CREDENTIAL = 'demo';

const FLIGHTS_INTERVALS: Array<number> = [10, 20, 30, 40, 50, 60, 70];

export {
  BUSIEST_AIRPORTS,
  DEMO_CREDENTIAL,
  FLIGHTS_INTERVALS,
};
